version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: https://xpcc.devb.zeak.io
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://xpcc.devb.zeak.io
    restart: unless-stopped
    